### PR TITLE
Option to use 48 or 53 bits to encode file length

### PR DESCRIPTION
**Pull request by regular**
As discussed in #2 
This also re-enables the restore/tests (now for all bitnesses)
Not sure about the "provide a number of bits as `offsetCodec`" shortcut and using numbers as properties in what `frame/offset-codecs` exports. What do you think?

### CODE REVIEW

**Comment by regular** [comment]
@dominictarr _ping_ :)

**Comment by dominictarr** [comment]
oh sorry, I thought this was merged. I'm getting sleepy now, I'll merge this tomorrow!

**Comment by regular** [comment]
Oh, don't worry, there's no rush.

Btw: do you prefer PRs on ssb or github these days? (if both repos exist).
I tend to check which one is newer to decide where to put the PR.

Have a good night!

**Comment by dominictarr** [comment]
thanks! merged into 3.2.0

**Comment by dominictarr** [comment]
newer is a good policy. I would like to do via git-ssb but the thing that is missing is a decent inbox/queue of open issues that I need to handle, so it's easy for things to slip past. For me, this is the number 1 thing that git-ssb needs most (cc @cel)

Also, for things that I hope to have a broader appeal outside of ssb internals (flume, pull-streams) I will use github too, because I hope to get users who arn't on ssb yet.

**Pull request merged**
