### PR TITLE
Add method to stream without cache

### PR DESCRIPTION
**Pull request by arj03**
When doing large reads the overhead in a cache in the getMeta function can be quite substantial (15%). Also if I know that I'm going to do a lot of reads that I will not need again, there is no reason to blow the cache for everyone else. 

I think it would be a good idea to use it [here](https://github.com/flumedb/flumedb/blob/master/index.js#L83) so that indexing is faster.

### CODE REVIEW

**Comment by dominictarr** [comment]
I think I'd rather have an option to disable cache on stream rather than a second method. It might also be good to use that option when, say, rebuilding views? I suggest `cache` option that defaults to false, so `{cache: false}` streams everything without cache.

**Comment by arj03** [comment]
Yes, it would be really useful for rebuilding views. I'll look into the cache option.

**Comment by arj03** [comment]
Thanks for pointing me in the right direction dominic. Adding it to pull-cursor is a more modular design.

**Comment by arj03** [comment]
This should be good now I think. Depends on https://github.com/dominictarr/pull-cursor/pull/2.

**Comment by arj03** [comment]
@dominictarr I merged this and bumped versions. The same with bench-flumelog 1.2.0 but I don't have permissions on npm to publish them. I did publish pull-cursor 3.0.0 though.

**Comment by dominictarr** [comment]
added you to flume-owners, now you have everything!

**Pull request merged**
