### PR TITLE
Fix legacy decode arg fallback

### PR DESCRIPTION
**Pull request by marcbachmann**

### CODE REVIEW

**Comment by marcbachmann** [comment]
Fixed in master

**Comment by marcbachmann** [comment]
Or not. @dominictarr you'll also need to update https://github.com/flumedb/flumelog-offset/commit/51fa6ab2c96ba8f5f856d260566a73bdcd433b38#diff-168726dbe96b3ce427e7fedce31bb0bcR25

;)

`(file, blockSize, codec)`

**Comment by marcbachmann** [comment]
breaking changes would be easier :)
but I don't know your preference in such a case.

**Comment by dominictarr** [comment]
sorry, it's fixed now 3.1.2

**Comment by dominictarr** [comment]
it's not that hard, you just took a strange approach, they key to supporting legacy code is to touch the code as little as possible

**Pull request closed without merging**
